// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.FeatureManagement.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Audience
    {
        /// <summary>
        /// Initializes a new instance of the Audience class.
        /// </summary>
        public Audience()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Audience class.
        /// </summary>
        public Audience(System.Guid featureId, System.Guid? id = default(System.Guid?), bool? isActive = default(bool?), IList<User> users = default(IList<User>), IList<GroupRollout> groupRollouts = default(IList<GroupRollout>), double? defaultRolloutPercentage = default(double?), string createdBy = default(string), System.DateTimeOffset? createdOn = default(System.DateTimeOffset?), string modifiedBy = default(string), System.DateTimeOffset? modifiedOn = default(System.DateTimeOffset?))
        {
            Id = id;
            FeatureId = featureId;
            IsActive = isActive;
            Users = users;
            GroupRollouts = groupRollouts;
            DefaultRolloutPercentage = defaultRolloutPercentage;
            CreatedBy = createdBy;
            CreatedOn = createdOn;
            ModifiedBy = modifiedBy;
            ModifiedOn = modifiedOn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "featureId")]
        public System.Guid FeatureId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "users")]
        public IList<User> Users { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupRollouts")]
        public IList<GroupRollout> GroupRollouts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "defaultRolloutPercentage")]
        public double? DefaultRolloutPercentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdOn")]
        public System.DateTimeOffset? CreatedOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedBy")]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedOn")]
        public System.DateTimeOffset? ModifiedOn { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
