// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.FeatureManagement.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Feature
    {
        /// <summary>
        /// Initializes a new instance of the Feature class.
        /// </summary>
        public Feature()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Feature class.
        /// </summary>
        public Feature(string name, System.Guid? id = default(System.Guid?), string description = default(string), bool? isEnabled = default(bool?), bool? isArchived = default(bool?), bool? alwaysOn = default(bool?), bool? alwaysOff = default(bool?), TimeWindow timeWindow = default(TimeWindow), RolloutPercentage rolloutPercentage = default(RolloutPercentage), Audience audience = default(Audience), IList<BrowserRestriction> browserRestrictions = default(IList<BrowserRestriction>), bool? hasFallbackFeature = default(bool?), string createdBy = default(string), System.DateTimeOffset? createdOn = default(System.DateTimeOffset?), string modifiedBy = default(string), System.DateTimeOffset? modifiedOn = default(System.DateTimeOffset?))
        {
            Id = id;
            Name = name;
            Description = description;
            IsEnabled = isEnabled;
            IsArchived = isArchived;
            AlwaysOn = alwaysOn;
            AlwaysOff = alwaysOff;
            TimeWindow = timeWindow;
            RolloutPercentage = rolloutPercentage;
            Audience = audience;
            BrowserRestrictions = browserRestrictions;
            HasFallbackFeature = hasFallbackFeature;
            CreatedBy = createdBy;
            CreatedOn = createdOn;
            ModifiedBy = modifiedBy;
            ModifiedOn = modifiedOn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isArchived")]
        public bool? IsArchived { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alwaysOn")]
        public bool? AlwaysOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alwaysOff")]
        public bool? AlwaysOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeWindow")]
        public TimeWindow TimeWindow { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rolloutPercentage")]
        public RolloutPercentage RolloutPercentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "audience")]
        public Audience Audience { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "browserRestrictions")]
        public IList<BrowserRestriction> BrowserRestrictions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasFallbackFeature")]
        public bool? HasFallbackFeature { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdOn")]
        public System.DateTimeOffset? CreatedOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedBy")]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedOn")]
        public System.DateTimeOffset? ModifiedOn { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (TimeWindow != null)
            {
                TimeWindow.Validate();
            }
            if (Audience != null)
            {
                Audience.Validate();
            }
            if (BrowserRestrictions != null)
            {
                foreach (var element in BrowserRestrictions)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
