// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.FeatureManagement.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GroupRollout
    {
        /// <summary>
        /// Initializes a new instance of the GroupRollout class.
        /// </summary>
        public GroupRollout()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupRollout class.
        /// </summary>
        public GroupRollout(System.Guid? id = default(System.Guid?), string name = default(string), double? rolloutPercentage = default(double?), string createdBy = default(string), System.DateTimeOffset? createdOn = default(System.DateTimeOffset?), string modifiedBy = default(string), System.DateTimeOffset? modifiedOn = default(System.DateTimeOffset?))
        {
            Id = id;
            Name = name;
            RolloutPercentage = rolloutPercentage;
            CreatedBy = createdBy;
            CreatedOn = createdOn;
            ModifiedBy = modifiedBy;
            ModifiedOn = modifiedOn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rolloutPercentage")]
        public double? RolloutPercentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdOn")]
        public System.DateTimeOffset? CreatedOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedBy")]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedOn")]
        public System.DateTimeOffset? ModifiedOn { get; set; }

    }
}
