// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.FeatureManagement.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RolloutPercentage
    {
        /// <summary>
        /// Initializes a new instance of the RolloutPercentage class.
        /// </summary>
        public RolloutPercentage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RolloutPercentage class.
        /// </summary>
        public RolloutPercentage(System.Guid? id = default(System.Guid?), System.Guid? featureId = default(System.Guid?), bool? isActive = default(bool?), int? percentage = default(int?), string createdBy = default(string), System.DateTimeOffset? createdOn = default(System.DateTimeOffset?), string modifiedBy = default(string), System.DateTimeOffset? modifiedOn = default(System.DateTimeOffset?))
        {
            Id = id;
            FeatureId = featureId;
            IsActive = isActive;
            Percentage = percentage;
            CreatedBy = createdBy;
            CreatedOn = createdOn;
            ModifiedBy = modifiedBy;
            ModifiedOn = modifiedOn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "featureId")]
        public System.Guid? FeatureId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "percentage")]
        public int? Percentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdOn")]
        public System.DateTimeOffset? CreatedOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedBy")]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedOn")]
        public System.DateTimeOffset? ModifiedOn { get; set; }

    }
}
